### ISSUE TITLE
JsonUtility Problem

### ISSUE THREAD

**Issue by erengaygusuz** [unity-game-framework/organization#1]
When I install your packages, I got some error massages at below:

Library\PackageCache\com.ugf.customsettings@3.4.0\Runtime\CustomSettingsPrefs.cs(37,27): error CS0103: The name 'JsonUtility' does not exist in the current context

Library\PackageCache\com.ugf.customsettings@3.4.0\Runtime\CustomSettingsFile.cs(40,27): error CS0103: The name 'JsonUtility' does not exist in the current context

Library\PackageCache\com.ugf.customsettings@3.4.0\Runtime\CustomSettingsPrefs.cs(48,13): error CS0103: The name 'JsonUtility' does not exist in the current context

Library\PackageCache\com.ugf.customsettings@3.4.0\Runtime\CustomSettingsFile.cs(55,13): error CS0103: The name 'JsonUtility' does not exist in the current context

How I get rid of this messages and also is there a starting point to use these packages? Any example?

**Comment by AlexanderVorobyov** [comment]
Hi @erengaygusuz, what packages do you have installed in project? (you can send me dependencies from `Packages/manifest.json` file)

Some packages may have outdated dependencies, but `com.ugf.customsettings` package had missing dependency and this issue has been fixed with latest release: https://github.com/unity-game-framework/ugf-customsettings/releases/tag/3.4.1

I suggest to update `com.ugf.customsettings` package up to `3.4.1` version manually.

**Comment by AlexanderVorobyov** [comment]
> also is there a starting point to use these packages? Any example?

Unfortunately packages lacks of documentations and any examples right now, but I consider to add them for some packages in future.

**Comment by erengaygusuz** [comment]
This is the inside of manifest.json.

{
  "dependencies": {
    "com.ugf.assetpipeline": "1.0.0",
    "com.ugf.csv": "1.0.0",
    "com.ugf.jsonnet": "1.3.0",
    "com.ugf.module.actions": "1.2.0",
    "com.ugf.module.scenes": "2.2.0",
    "com.ugf.module.serialize": "3.1.0",
    "com.ugf.serialize.jsonnet": "1.0.1",
    "com.ugf.serialize.yamldotnet": "1.0.0",
    "com.ugf.ui": "1.0.0",
    "com.ugf.webrequests": "1.0.0",
    "com.ugf.yaml": "1.1.0"
  },
  "scopedRegistries": [
    {
      "name": "Unity Game Framework",
      "url": "https://unitygameframework.jfrog.io/artifactory/api/npm/default",
      "scopes": [
        "com.ugf"
      ]
    }
  ]
}

**Comment by erengaygusuz** [comment]
Can I send you a message on github? There are so many packages. I would like to send a photo about them. If you apply my request on Linkedin, I can send you a photo

**Comment by erengaygusuz** [comment]
Firstly, I go to that page: https://github.com/unity-game-framework/organization/blob/main/docs/install-packages.md and changed manifest.json like this: 

{
  "dependencies": {},
  "scopedRegistries": [
    {
      "name": "Unity Game Framework",
      "url": "https://unitygameframework.jfrog.io/artifactory/api/npm/default",
      "scopes": [
        "com.ugf"
      ]
    }
  ]
}

After that, in package manager your packages appeared and I downloaded them one by one except preview packages.

**Comment by AlexanderVorobyov** [comment]
> Can I send you a message on github? There are so many packages. I would like to send a photo about them. If you apply my request on Linkedin, I can send you a photo

You can post any images here.

**Comment by erengaygusuz** [comment]
Okay. There arent any icon for photo uploading, maybe I couldnt see, but anyway draging drop works. 

These are the images:

![Capture](https://user-images.githubusercontent.com/56393357/125065752-e1b1d900-e0ba-11eb-9274-f1cc30f8ed25.PNG)

![Capture1](https://user-images.githubusercontent.com/56393357/125065770-e70f2380-e0ba-11eb-9d94-de1df9b92dd1.PNG)

**Comment by AlexanderVorobyov** [comment]
> except preview packages.

To display preview packages follow this manual under the _Advanced Settings_ section: https://docs.unity3d.com/2021.1/Documentation/Manual/class-PackageManager.html

**Comment by erengaygusuz** [comment]
No, there is no problem to display them. I can, but thanks. 

I just did not download them because of their preview situation

Do I have to download also these preview packages?

**Comment by AlexanderVorobyov** [comment]
> Do I have to download also these preview packages?

Yes, in current stage of development, I recommend to install latest versions of packages, because some of the old _non-preview_ package has bugs and such errors.

Try to update all packages to latest version, even preview ones, that should fix the errors.

**Comment by erengaygusuz** [comment]
Okay, I'll update all packages to latest version.

**Comment by AlexanderVorobyov** [comment]
I will update _Install Package_ documentation to reflect this problem, thanks!

**Comment by erengaygusuz** [comment]
Your welcome. After updating all packages, there are still error messages. 

![Capture](https://user-images.githubusercontent.com/56393357/125067464-fa22f300-e0bc-11eb-98a2-e32c0c320990.PNG)

![Capture1](https://user-images.githubusercontent.com/56393357/125067474-fd1de380-e0bc-11eb-8a8a-cb6cd4c47ee1.PNG)

**Comment by AlexanderVorobyov** [comment]
Yes, you need to update some other package to latest preview release too, because some _Module_ preview packages can not work with other non-preview packages.

This such packages as: _UGF.Module.Actions_, _UGF.Module.Scenes_, _UGF.Module.Serialize_ and _UGF.Module.Update_.

**Comment by erengaygusuz** [comment]
> Yes, you need to update some other package to latest preview release too, because some _Module_ preview packages can not work with other non-preview packages.
> 
> This such packages as: _UGF.Module.Actions_, _UGF.Module.Scenes_, _UGF.Module.Serialize_ and _UGF.Module.Update_.

I did but still there are three error messages..

**Comment by AlexanderVorobyov** [comment]
What version of _Unity_ do you use?

Some latest module packages have requirement for `2021.1` version of _Unity_.

**Comment by erengaygusuz** [comment]
2020.3.2f1. Hm I will change the version of Unity to 2021.1 or above

I cannot use an alpha or beta version of Unity 2021 am i right?

I will download Unity 2021.1.14 f1

**Comment by erengaygusuz** [comment]
I cannot use an alpha or beta version of Unity 2021 am i right?

**Comment by AlexanderVorobyov** [comment]
> I cannot use an alpha or beta version of Unity 2021 am i right?
> I will download Unity 2021.1.14 f1

Latest version of `2021.1` should be enough.

**Comment by erengaygusuz** [comment]
> > I cannot use an alpha or beta version of Unity 2021 am i right?
> > I will download Unity 2021.1.14 f1
> 
> Latest version of `2021.1` should be enough.

Okay, I am downloading right now.

**Comment by erengaygusuz** [comment]
I installed Unity 2021.1 after that updated all the packages to latest version, and error messages disappeared.

Thanks for your help. :) Now, I will try to understand your packages to use them in my projects.

**Comment by AlexanderVorobyov** [comment]
You are welcome!
